(() => {
  const asset=name=>new URL(`../assets/${name}`,import.meta.url).href;
  const expertImage=document.querySelector('.expert-photo img');expertImage.src=asset('customs-team-documentary.png');expertImage.alt='Especialistas logísticos revisando documentación aduanal en oficina';
  const scenarioTabs=[...document.querySelectorAll('.scenario-tab')];scenarioTabs[0].dataset.image=asset('air-freight-ramp.png');scenarioTabs[1].dataset.image=asset('port-blue-hour.png');scenarioTabs[2].dataset.image=asset('road-freight-documentary.png');scenarioTabs[2].dataset.alt='Transporte terrestre coordinado en un corredor regional';
  const menu=document.querySelector('.menu'),navLinks=document.querySelector('.nav-links');
  menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Abrir menú':'Cerrar menú');navLinks.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});
  navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');navLinks.classList.remove('open');document.body.classList.remove('menu-open')}));
  const bindTabs=(selector,image,title,copy,kicker)=>document.querySelectorAll(selector).forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll(selector).forEach(t=>t.setAttribute('aria-selected','false'));tab.setAttribute('aria-selected','true');const img=document.querySelector(image);img.src=tab.dataset.image;img.alt=tab.dataset.alt;document.querySelector(title).textContent=tab.dataset.title;document.querySelector(copy).textContent=tab.dataset.description||tab.dataset.copy;if(kicker)document.querySelector(kicker).textContent=tab.dataset.label||tab.dataset.kicker}));
  bindTabs('.scenario-tab','#scenario-image','#scenario-title','#scenario-copy','#scenario-kicker');
  const corridorTabs=[...document.querySelectorAll('.corridor-tabs [role="tab"]')],corridorPanels=[...document.querySelectorAll('.corridor-evidence>[role="tabpanel"]')],corridorRoutes=[...document.querySelectorAll('.corridor-route')],corridorStage=document.querySelector('.corridor-stage'),originPoint=document.querySelector('[data-point="origin"]'),transitPoint=document.querySelector('[data-point="transit"]');
  const corridorLabels={pacific:['Asia / Shanghai · origen','Acajutla · ingreso'],north:['Norteamérica · origen','Conexión regional'],europe:['Europa · origen','Gateway · tránsito']};
  const corridorGeometry={pacific:'M835 205 Q566 72 260 274 Q248 284 237 288',north:'M205 205 Q252 218 282 267 Q260 278 237 288',europe:'M520 155 Q470 125 445 210 Q340 220 237 288'};
  corridorRoutes.forEach(route=>route.setAttribute('d',corridorGeometry[route.dataset.route]));
  const routesCanvas=document.querySelector('.corridor-stage .routes'),svgNS='http://www.w3.org/2000/svg';
  const contextRoutes=['M835 205 Q570 55 205 205','M835 205 Q690 98 520 155','M835 205 Q560 92 237 288','M520 155 Q360 90 205 205','M520 155 Q390 160 237 288','M205 205 Q245 235 237 288','M205 205 Q230 300 320 382','M320 382 Q430 235 520 155','M760 330 Q520 245 320 382','M760 330 Q510 195 237 288','M660 240 Q440 135 205 205','M90 300 Q180 250 237 288'];
  const contextGroup=document.createElementNS(svgNS,'g');contextGroup.setAttribute('class','context-routes');contextGroup.setAttribute('aria-hidden','true');contextRoutes.forEach(data=>{const path=document.createElementNS(svgNS,'path');path.setAttribute('d',data);contextGroup.appendChild(path)});routesCanvas.insertBefore(contextGroup,routesCanvas.querySelector('.corridor-route'));
  const activateCorridor=(tab,focus=false)=>{const id=tab.dataset.corridor;corridorTabs.forEach(item=>{const active=item===tab;item.setAttribute('aria-selected',String(active));item.tabIndex=active?0:-1});corridorPanels.forEach(panel=>panel.hidden=panel.id!==`corridor-${id}`);corridorRoutes.forEach(route=>route.classList.toggle('is-active',route.dataset.route===id));corridorStage.dataset.corridor=id;originPoint.textContent=corridorLabels[id][0];transitPoint.textContent=corridorLabels[id][1];if(focus)tab.focus()};
  corridorTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activateCorridor(tab));tab.addEventListener('keydown',event=>{const keys=['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();let next=index;if(event.key==='ArrowRight'||event.key==='ArrowDown')next=(index+1)%corridorTabs.length;if(event.key==='ArrowLeft'||event.key==='ArrowUp')next=(index-1+corridorTabs.length)%corridorTabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=corridorTabs.length-1;activateCorridor(corridorTabs[next],true)})});
  activateCorridor(corridorTabs.find(tab=>tab.getAttribute('aria-selected')==='true')||corridorTabs[0]);
  const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;if(reduced){document.querySelectorAll('.reveal').forEach(e=>e.classList.add('in'))}else{const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}
})();
